application: indelhi-orchin
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /static
  static_dir: static

- url: /db
  script: database.app

- url: /db/\S+
  script: database.app

- url: /tests
  script: tests.app

- url: /\S+
  script: main.app

- url: /template
  static_dir: template

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest